### ISSUE TITLE
Overlay window not showing in Windows10

### ISSUE THREAD

**Issue by AhmetBilgin** [farzd/keydox#3]
Hi,
I wanted to use your app to visualize my ergodox layout, as I'm still getting used to it.
But I have a problem with the main window which is not showing on my Windows10 machine.

Is there a way to enable logging to figure out why?
I can see that the app is running and in the taskbar I can see a preview of the layout when hovering over the app's icon.
Please see the attached picture.
![ergodox-layout-visualizer](https://user-images.githubusercontent.com/20398514/79265939-268a9800-7e97-11ea-9588-0d4383cbdc25.png)

**Comment by farzd** [comment]
Hey,
Thanks for trying this out. I just put it together quickly so you'll have to add comments yourself
However i can try help you out but i dont understand the issue, are you saying that the app does not show by default? It will be difficult for me to debug as i only have OSX

**Comment by farzd** [comment]
This works for windows only https://github.com/Invvard/EZLayoutDisplay, perhaps its a better alternative for windows users

**Comment by AhmetBilgin** [comment]
Hi Farzad,

what I meant is that the main-window is never visible when starting the App.
I only see the Icon off the app in the taskbar and the little preview of it
when hovering over the taskbar icon.
Did I Understand you correct, that I should put debug logging comments in
the source code myself?
I'm a softwaredeveloper, but Not familiär with the electron Software Stack.
I would have to dig in first.

I prefer your App over the EZ Layout Display, because your App has the
Always on top overlay😊

Maybe you could narrow down where to put log messages.

Thanks for helping!

Best regards,
Ahmer


Farzad Qasim <notifications@github.com> schrieb am Mi., 15. Apr. 2020,
09:53:

**Comment by farzd** [comment]
i think it must be to do with the transaprency setting 

https://www.electronjs.org/docs/api/frameless-window#limitations
```On Windows operating systems, transparent windows will not work when DWM is disabled.```

can you try turn this off inside main.js [either change to false or remove it completley]
https://github.com/farzd/keydox/blob/master/main.js#L32

**Comment by AhmetBilgin** [comment]
Hi Farzad,
setting transparent=false didn't help. But I think you're right with this
transparency issues under windows. There are plenty of reported bugs filed
for the electron framework regarding this.
Do you have any other hints?
Your idea with turning the transparency of, to see if the main window will
be visible was good. Any other ideas in this direction?
I'll do some research on my side.

Have a nice weekend and stay healthy!
Ahmet

Am Do., 16. Apr. 2020 um 10:14 Uhr schrieb Farzad Qasim <
notifications@github.com>:

**Comment by AhmetBilgin** [comment]
Hi,
I got it working.
The problem was the main-window coordinates I guess.

I changed the following:

   - html/style.css
      - Resized to:
         - width: 800px;
         - height: 400px;
      - diff of main.js (to position the main window in the bottom right
   corner):

 function createWindow() {

   let display = screen.getPrimaryDisplay()

-  let height = display.bounds.height

+  const { width, height } = display.workAreaSize

   trays = new Tray(iconPath)


   mainWindow = new BrowserWindow({

-    width: 500,

-    height: 190,

-    x: 0,

-    y: height,

+    width,

+    height,

+    width: 800,

+    height: 400,

+    x: width - 800,

+    y: height - 300,

+    opacity: 0.7,

     frame: false,

     transparent: true

   })


   - Also I had to change the globalShortcuts from the CMD-Key to the
   ALT-Key:

-  globalShortcut.register('Command+1', () => {

+  globalShortcut.register('Alt+1', () => {

     if (mainWindow.isVisible()) {

       changeImg('1', mainWindow)

     }

   })

Right now I'm learning a little bit JavaScript so that I'm able to retrieve
my key bindings directly from the ez-online configurator.
I'll fork your repo and Implement this :)

Thank You!
I think you can close this issue.

Am Do., 16. Apr. 2020 um 10:14 Uhr schrieb Farzad Qasim <
notifications@github.com>:

**Comment by farzd** [comment]
glad you got it working not sure why res was an issue but hopefully others can see this if they have problems on windows OS too.
